CREATE TABLE [Staging_CRM].[contact] (
    [contactid]                             VARCHAR (50)   NULL,
    [ownerid]                               VARCHAR (50)   NULL,
    [customertypecode]                      VARCHAR (10)   NULL,
    [customertypecodename]                  VARCHAR (50)   NULL,
    [firstname]                             VARCHAR (50)   NULL,
    [middlename]                            VARCHAR (50)   NULL,
    [lastname]                              VARCHAR (50)   NULL,
    [suffix]                                VARCHAR (10)   NULL,
    [nickname]                              VARCHAR (50)   NULL,
    [salutation]                            VARCHAR (50)   NULL,
    [gendercode]                            VARCHAR (10)   NULL,
    [gendercodename]                        VARCHAR (50)   NULL,
    [birthdate]                             VARCHAR (20)   NULL,
    [dcp_mothersmaidenname]                 VARCHAR (50)   NULL,
    [spousesname]                           VARCHAR (50)   NULL,
    [anniversary]                           VARCHAR (20)   NULL,
    [haschildrencode]                       VARCHAR (10)   NULL,
    [haschildrencodename]                   VARCHAR (50)   NULL,
    [familystatuscode]                      VARCHAR (10)   NULL,
    [familystatuscodename]                  VARCHAR (50)   NULL,
    [dcp_ethnicorigincode]                  VARCHAR (10)   NULL,
    [dcp_ethnicorigincodename]              VARCHAR (50)   NULL,
    [address1_line1]                        VARCHAR (255)  NULL,
    [address1_line2]                        VARCHAR (255)  NULL,
    [address1_city]                         VARCHAR (255)  NULL,
    [address1_stateorprovince]              VARCHAR (255)  NULL,
    [address1_country]                      VARCHAR (255)  NULL,
    [address1_postalcode]                   VARCHAR (255)  NULL,
    [dcp_primaryphone]                      VARCHAR (10)   NULL,
    [dcp_primaryphonename]                  VARCHAR (50)   NULL,
    [telephone1]                            VARCHAR (255)  NULL,
    [telephone2]                            VARCHAR (255)  NULL,
    [mobilephone]                           VARCHAR (50)   NULL,
    [emailaddress1]                         VARCHAR (255)  NULL,
    [entityimage_url]                       VARCHAR (255)  NULL,
    [dcp_emergencycontact]                  VARCHAR (255)  NULL,
    [dcp_emergencycontactphonenumber]       VARCHAR (50)   NULL,
    [dcp_driverslicensestate]               VARCHAR (10)   NULL,
    [dcp_driverslicensestatename]           VARCHAR (50)   NULL,
    [dcp_driverslicensestateorprovince]     VARCHAR (50)   NULL,
    [dcp_driverslicensenumber]              VARCHAR (50)   NULL,
    [dcp_driverslicenseexpiration]          VARCHAR (20)   NULL,
    [dcp_autoinsurancecompany]              VARCHAR (255)  NULL,
    [dcp_autoinsurancepolicy]               VARCHAR (50)   NULL,
    [dcp_autoinsuranceexpiration]           VARCHAR (20)   NULL,
    [jobtitle]                              VARCHAR (255)  NULL,
    [dcp_executive]                         VARCHAR (10)   NULL,
    [dcp_executivename]                     VARCHAR (50)   NULL,
    [dcp_chaplainflag]                      VARCHAR (10)   NULL,
    [dcp_chaplainflagname]                  VARCHAR (50)   NULL,
    [dcp_hiredate]                          VARCHAR (20)   NULL,
    [dcp_ordainedflag]                      VARCHAR (10)   NULL,
    [dcp_ordainedflagname]                  VARCHAR (50)   NULL,
    [dcp_ordainedagency]                    VARCHAR (255)  NULL,
    [dcp_ordaineddate]                      VARCHAR (20)   NULL,
    [dcp_licensedflag]                      VARCHAR (10)   NULL,
    [dcp_licensedflagname]                  VARCHAR (50)   NULL,
    [dcp_licensedagency]                    VARCHAR (255)  NULL,
    [dcp_licenseddate]                      VARCHAR (20)   NULL,
    [dcp_churchcommissionedflag]            VARCHAR (10)   NULL,
    [dcp_churchcommissionedflagname]        VARCHAR (50)   NULL,
    [dcp_churchcommissioneddate]            VARCHAR (20)   NULL,
    [dcp_churchcommissionedname]            VARCHAR (255)  NULL,
    [dcp_churchcommissionedcity]            VARCHAR (255)  NULL,
    [dcp_churchcommissionedstate]           VARCHAR (255)  NULL,
    [dcp_irsapprovedministerflag]           VARCHAR (10)   NULL,
    [dcp_irsapprovedministerflagname]       VARCHAR (50)   NULL,
    [dcp_denominationcode]                  VARCHAR (10)   NULL,
    [dcp_denominationcodename]              VARCHAR (50)   NULL,
    [dcp_denominationalendorsementflag]     VARCHAR (10)   NULL,
    [dcp_denominationalendorsementflagname] VARCHAR (50)   NULL,
    [dcp_denominationalendorsementagency]   VARCHAR (255)  NULL,
    [dcp_denominationalendorsementdate]     VARCHAR (20)   NULL,
    [cat_employeestatusglobal]              VARCHAR (10)   NULL,
    [cat_employeestatusglobalname]          VARCHAR (50)   NULL,
    [statuscode]                            VARCHAR (10)   NULL,
    [statuscodename]                        VARCHAR (50)   NULL,
    [modifiedon]                            VARCHAR (20)   NULL,
    [InsertDate]                            DATETIME       CONSTRAINT [DF__contact__InsertD__566B5B6C] DEFAULT (getdate()) NOT NULL,
    [EmployeeKey]                           INT            NULL,
    [DurableEmployeeKey]                    INT            NULL,
    [EmployeeName]                          VARCHAR (100)  NULL,
    [DateOfBirth]                           DATE           NULL,
    [Address]                               VARCHAR (500)  NULL,
    [DriversLicenseExpirationDate]          DATE           NULL,
    [AutoInsuranceExpirationDate]           DATE           NULL,
    [HireDate]                              DATE           NULL,
    [MaximumWeeklyHours]                    MONEY          NULL,
    [PayFrequency]                          VARCHAR (20)   NULL,
    [PayAmount]                             MONEY          NULL,
    [Chaplain]                              BIT            NULL,
    [IRSApprovedMinister]                   BIT            NULL,
    [DenominationalEndorsement]             BIT            NULL,
    [EndorsementDate]                       DATE           NULL,
    [Ordained]                              BIT            NULL,
    [OrdainedDate]                          DATE           NULL,
    [Licensed]                              BIT            NULL,
    [LicensedDate]                          DATE           NULL,
    [ChurchCommissioned]                    BIT            NULL,
    [CommissionedDate]                      DATE           NULL,
    [ImageURL]                              VARCHAR (1000) NULL,
    [Active]                                BIT            NULL,
    [Type_1_Change]                         BIT            NULL,
    [Type_2_Change]                         BIT            NULL,
    [Type_2_Exception]                      BIT            NULL
);















